#screen var
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 650
SCREEN_TITLE = "game"

#vol var
MUSIC_VOLUME = 0.5

START = 0
END = 2000
STEP = 50

#scaling var
CHARACTER_SCALING = 1.2
TILE_SCALING = 0.5
SPRITE_SCALING_BULLET = 0.25
AR_SCALING = 1.4
ENEMY_SCALING = 1.5

#pixel var
SPRITE_PIXEL_SIZE = 128
GRID_PIXEL_SIZE = (SPRITE_PIXEL_SIZE * TILE_SCALING)

#player mechanics
PLAYER_MOVEMENT_SPEED = 5
GRAVITY = 1
PLAYER_JUMP_SPEED = 20
BULLET_SPEED = 25


#enemy mechanics
ENEMY_ACCELERATION_RATE = 0.1
ENEMY_FRICTION = 0.05
ENEMY_MAX_SPEED = 6
ENEMY_TURN_RATE = 1
ENEMY_MAX_WONDER_SPEED = 1


# scrapped var ENEMY_MAX_WONDER_SPEED = 1

# How many pixels to keep as a minimum margin between the character
# and the edge of the screen.
LEFT_VIEWPORT_MARGIN = 250
RIGHT_VIEWPORT_MARGIN = 250
BOTTOM_VIEWPORT_MARGIN = 150
TOP_VIEWPORT_MARGIN = 100

PLAYER_START_X = 80
PLAYER_START_Y = 260

AMBIENT_COLOR = (10,10, 10)
PLAYER_LIGHT_RADIUS = 150
PLAYER_LIGHT_MODE = 'soft'
PLAYER_LIGHT_COLOR = (300, 300, 300)

#frame rates
PLAYER_FRAMES = 32
PLAYER_FRAMES_PER_TEXTURE = 3
ENEMY_WALK_FRAMES = 7
ENEMY_ATTACK_FRAMES = 25
ENEMY_WALK_FRAMES_PER_TEXTURE = 4
ENEMY_ATTACK_FRAMES_PER_TEXTURE =1

# Constants used to track if the player is facing left or right
RIGHT_FACING = 0
LEFT_FACING = 1

ENEMY_LEFT_FACING = 1
ENEMY_RIGHT_FACING = 0